server:
  port: 7006
  tomcat:
    uri-encoding: UTF-8
    max-threads: 800
    min-spare-threads: 30

spring:
  profiles:
    active: dev
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss
  datasource:
    url: jdbc:mysql://localhost:3306/dreamland_attachment_test?useUnicode=true&characterEncoding=utf8&serverTimezone=UTC&zeroDateTimeBehavior=convertToNull&useSSL=true
    username: root
    password: root@12345
  application:
    name: attachment-api
  redis:
    host: 127.0.0.1
eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true       #发现服务
    register-with-eureka: true #注册服务
    service-url:
      defaultZone: http://localhost:7000/eureka/

logging:
  level:
    com.fanling.dreamland.attachment: info
    org.springframework: warn
  file: D:/logs/dreamland/attachment-api/wraper.log

mybatis:
  typeAliasesPackage: com.fanling.dreamland.attachment.entity
  mapperLocations: classpath*:mybatis/mapper/*Mapper.xml
  configLocation: classpath:mybatis/mybatis-config.xml

pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql

fdfs:
  soTimeout: 1500
  connectTimeout: 600
  trackerList: 172.30.0.4:22122