server:
  port: 7001
spring:
  profiles:
    active: dev
  application:
    name: gateway
  datasource:
    url: jdbc:mysql://localhost:3306/dreamland_gateway_test?useUnicode=true&characterEncoding=utf8&serverTimezone=UTC&zeroDateTimeBehavior=convertToNull&useSSL=true
    username: root
    password: root@12345
  redis:
    host: 127.0.0.1
zuul:
  ignored-services: "*"
  routes:
    auth-api:
      path: /auth-api/**
      serviceId: auth-api
    service-api:
      path: /service-api/**
      serviceId: service-api
    attachment-api:
      path: /attachment-api/**
      serviceId: attachment-api
  host:
    connect-timeout-millis: 15000         #HTTP连接超时要比Hystrix的大
    socket-timeout-millis: 60000          #socket超时

ribbon:
  ReadTimeout: 60000
  ConnectTimeout: 60000

eureka:
  client:
    fetch-registry: true       #发现服务
    register-with-eureka: true #注册服务
    service-url:
      defaultZone: http://localhost:7000/eureka/
logging:
  level:
    com.fanling.dreamland: info
    org.springframework: warn
  file: D:/logs/dreamland/geteway-service/wraper.log