dreamland:
  name: Admin
  version: 1.0.0
  profile: D:/profile/

server:
  port: 9000
  servlet:
    context-path: /admin
  tomcat:
    uri-encoding: UTF-8
    max-threads: 800
    min-spare-threads: 30

logging:
  level:
    com.fanling.dreamland: debug
    org.springframework: warn

spring:
  thymeleaf:
    mode: HTML
    encoding: utf-8
    cache: false
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss
  servlet:
    multipart:
      max-file-size:  10MB
      max-request-size:  20MB
  devtools:
    restart:
      enabled: true

mybatis:
  typeAliasesPackage: com.fanling.dreamland.domain
  mapperLocations: classpath:mybatis/**/*Mapper.xml
  configLocation: classpath:mybatis/mybatis-config.xml

pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql

shiro:
  user:
    indexUrl: /index
  cookie:
    domain:
  session:
    dbSyncPeriod: 1

xss:
  enabled: true
  excludes:
  urlPatterns: /system/*,