server:
  port: 7000
spring:
  profiles:
    active: dev
  application:
    name: eureka-service
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/dreamland_eureka_test?useUnicode=true&characterEncoding=utf8&serverTimezone=UTC&zeroDateTimeBehavior=convertToNull&useSSL=true
    username: root
    password: root@12345

eureka:
  instance:
    hostname: localhost
  client:
    register-with-eureka: false
    fetch-registry: false
    healthcheck:
      enabled: true
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
  #项目日志
logging:
  level:
    com.fanling.dreamland: info
    org.springframework: warn
  file: D:/logs/dreamland/eureka-service/wraper.log