server:
  port: 7000
spring:
  profiles:
    active: prod
  application:
    name: eureka-service
eureka:
  instance:
    hostname: 172.30.0.4
  client:
    register-with-eureka: false
    fetch-registry: false
    healthcheck:
      enabled: true
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
  #项目日志
logging:
  level:
    com.fanling.dreamland.eureka: info
    org.springframework: warn
  file: /opt/modules/logs/dreamland/eureka-service/wraper.log