dreamland:
  name: eureka
  version: 1.0.0

server:
  port: 8800
  servlet:
    context-path: /eurekaServer
  tomcat:
    uri-encoding: UTF-8
    max-threads: 800
    min-spare-threads: 30

logging:
  level:
    com.jwt.bigdata: info
    org.springframework: warn
    org.spring.springboot.dao: warn

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://localhost:${server.port}${server.servlet.context-path}/eureka/
  server:
    enableSelfPreservation: false