server:
  port: 9000
  servlet:
    context-path: /admin
  tomcat:
    uri-encoding: UTF-8
    max-threads: 800
    min-spare-threads: 30

logging:
  level:
    com.fanling.dreamland: debug
    org.springframework: warn

spring:
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss
  servlet:
    multipart:
      max-file-size:  10MB
      max-request-size:  20MB
  devtools:
    restart:
      enabled: true
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/jwt_open_test?useUnicode=true&characterEncoding=utf8&serverTimezone=UTC&zeroDateTimeBehavior=convertToNull&useSSL=true
    username: root
    password: root@12345
  redis:
    database: 0
    host: 127.0.0.1
    #password: myRedis_IS_CLOSED
    port: 6379
    timeout: 300

mybatis:
  typeAliasesPackage: com.fanling.dreamland.domain
  mapperLocations: classpath*:mapper/**/*Mapper.xml
  configLocation: classpath:mapper/mybatis-config.xml