server:
  port: 7006
  tomcat:
    uri-encoding: UTF-8
    max-threads: 800
    min-spare-threads: 30

spring:
  profiles:
    active: prod
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss
  datasource:
    url: jdbc:mysql://172.30.0.4:3306/dreamland_attachment?useUnicode=true&characterEncoding=utf8&serverTimezone=UTC&zeroDateTimeBehavior=convertToNull&useSSL=true
    username: docker
    password: docker@12345
  application:
    name: attachment-api
  redis:
    host: 172.30.0.4

eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true       #发现服务
    register-with-eureka: true #注册服务
    service-url:
      defaultZone: http://172.30.0.4:7000/eureka/

logging:
  level:
    com.fanling.dreamland: info
    org.springframework: warn
  file: /opt/modules/logs/dreamland/attachment-api/wraper.log

mybatis:
  typeAliasesPackage: com.fanling.dreamland.entity
  mapperLocations: classpath*:mybatis/mapper/*Mapper.xml
  configLocation: classpath:mybatis/mybatis-config.xml

pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql

fdfs:
  soTimeout: 1500
  connectTimeout: 600
  trackerList: 172.30.0.4:22122