server:
  port: 7003
  tomcat:
    uri-encoding: UTF-8
    max-threads: 800
    min-spare-threads: 30

spring:
  profiles:
    active: prod
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss
  servlet:
    multipart:
      max-file-size:  10MB
      max-request-size:  20MB
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/dreamland_auth?useUnicode=true&characterEncoding=utf8&serverTimezone=UTC&zeroDateTimeBehavior=convertToNull&useSSL=true
    username: root
    password: root@12345
  application:
    name: auth-api
  redis:
    host: 127.0.0.1

eureka:
  client:
    fetch-registry: true       #发现服务
    register-with-eureka: true #注册服务
    service-url:
      defaultZone: http://localhost:7000/eureka/

feign:
  hystrix:
    enabled: true # 开启Feign熔断

logging:
  level:
    com.fanling.dreamland: info
    org.springframework: warn
  file: /opt/modules/logs/dreamland/auth-api/wraper.log

mybatis:
  typeAliasesPackage: com.fanling.dreamland.entity
  mapperLocations: classpath*:mybatis/mapper/*Mapper.xml
  configLocation: classpath:mybatis/mybatis-config.xml

pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql